### PR TITLE
Take advantage of new fwd decl in VecGeom

### PR DESCRIPTION
**Pull request by pcanal**
This requires the following VecGeom MR: https://gitlab.cern.ch/VecGeom/VecGeom/-/merge_requests/800

### CODE REVIEW

**Comment by sethrj** [comment]
Thanks @pcanal . Should we wait for the next tag do you think, or just update the CI and development platforms as soon as the PR goes through? This will be a breaking change.

**Comment by pcanal** [comment]
I think we can wait until a tag or another reason to update the VecGeom requirement as this is a non-functional change.

**Comment by sethrj** [comment]
Sounds good, I'm going to mark as draft until that happens -- we can do the Docker CI update on this branch.

**Comment by sethrj** [comment]
Changes bundled into #222

**Pull request closed without merging**
