### PR TITLE
Improve substep estimator for highly curved tracks

### PR DESCRIPTION
**Pull request by sethrj**
We've run into the pathological problem a few times of having low-energy electrons in a vacuum: extremely long step lengths, very short radius of curvature. One issue with the chord estimator is that its step update is based on the assumption that the step is a very small arc length, whereas in the worst cases the requested step length could be hundreds of circles along a helical path.

Here's the current estimator algorithm's guess of the chord length as a function of step length: it should basically always be 2 after a full turn, but it reduces back to zero whenever the midpoint of the step is colinear with the endpoint.
chord-estimate

Using some trig and the "small theta" assumption it's possible to check for consistency by using the distance between the start and endpoints of the curve. (This does require the addition of a new "epsilon".) In the unit tests we get much improved behavior for low energy electrons and long steps, because we don't accidentally overestimate the length to be traveled. I suspect this will improve behavior in CMS.

For the CMS field regression problem, this seems to increase the average steps per primary by a fraction of a percent, but it increases the number of step iterations by 5–30% . The total time doesn't change much though.

https://celeritas-project.github.io/celeritas/dev/d3/dd9/classceleritas_1_1_field_driver.html

### CODE REVIEW

**Comment by sethrj** [comment]
The change to the low-energy "celeriton" along-step test illustrates the change between old and new.
Old:
```
  + step 0.0936215 to {0,-0.013388,6.99613} by way of {0,0.0208151,6.97999} -> dchord=0.0250012 -> scale by 1 - 2.30142e-05
  + step 0.0936193 to {0,-0.0133876,6.99613} by way of {0,0.0208148,6.97999} -> dchord=0.0250006 -> converged
 - accurate advance to 0.0936193 with initial step 6.38348e+15
  + integrating substep 0.0936193 from {0,0,7}
   * one good step
    # apply step 0.0936193 -> err/eps=487.816 -> scale by 0.191504
    # apply step 0.0179285 -> err/eps=173.642 -> scale by 0.24793
    # apply step 0.00444501 -> err/eps=0.512312 -> converged
  + integrated substep 0.0936193 -> 0.00444501, proposed step 0.00457307
...
    81 remaining
  + integrating substep 0.00125861 from {0,0.000816017,6.9975}
   * one good step
    # apply step 0.00125861 -> err/eps=0.000841529 -> converged
  + integrated substep 0.00125861 -> 0.00125861, proposed step 0.0046679 -> complete
==> substep 0.0936193
```
New:
```
  + step 0.0118496 to {0,0.00405813,6.99878} by way of {0,0.0035389,7.004} -> dchord=0.00484503, dist_err_sq=1.25535 -> way too long: scale by 1 - 0.55374
  + step 0.00528801 to {0,0.00316562,7.00371} by way of {0,0.00090442,7.00243} -> dchord=0.00088704, dist_err_sq=1.03906 -> converged
 - accurate advance to 0.00528801 with initial step 2.84167e+16
  + integrating substep 0.00528801 from {0,0,7}
   * one good step
    # apply step 0.00528801 -> err/eps=1.2422 -> scale by 0.8525
    # apply step 0.00450802 -> err/eps=0.551986 -> converged
  + integrated substep 0.00528801 -> 0.00450802, proposed step 0.00456923
    100 remaining
  + integrating substep 0.000779982 from {0,0.00240713,7.00349}
   * one good step
    # apply step 0.000779982 -> err/eps=9.05526e-05 -> converged
  + integrated substep 0.000779982 -> 0.000779982, proposed step 0.00389991 -> complete
==> substep 0.00528801
```

So the old chord estimator vastly overestimates the original chord length and so ends up doing a bunch more substep iterations. Both substeps *do* converge via discretization error to the same length, but the old way ends up doing a lot more.

**Comment by whokion** [comment]
General comment:  Nothing wrong with this type of fine optimization and refinement for the field driver, but it may also overlook other places where overall simulation should be treated in more practical and realistic ways.  As long as usual HEP experiments concerns (which is our first target), there are three major systems to deal with 1) tracker where particle tracking is critical for the relatively high energy particle with an accurate field stepper (say, above O(1GeV), for example, for LHC experiments) while low energy particle tracking may not be important (as they will not be reconstructed for physics), 2) calorimeters where simulated energy deposition is more important than particle tracking itself as lower energy particles will die out quickly (so likely confined in local area) and the fine tracking is relatively not important for them as they does not fly long distance in a dense calorimeter material, 3) muon detector where both tracking and energy deposition are important, but again only for high energy particles for tracing muon signals (or other survived hadrons from beam collisions or external sources such as cosmic rays, which will be backgrounds for muon identification).  So the fine treatment for this type pathological problem may be over-preventive before optimizing simulation in other places first (for example, ruling out production of such a low particle which can fly a long distance from physics processes, high-level tracking cuts, a step limit and so on.  Also, estimating performance with a specific case with a specific set of field parameters may not be projective or representive for overall simulation efficiency.  Nevertheless,  a good set of field parameters how to apply and optimize the use of any particle stepper within in its validity is necessary and explored in addition to both absolute and relative error control mechanisms.  The question is how to balance the overall efficiency without sacrificing the quality of simulation.

**Comment by sethrj** [comment]
That's fair. The reason I'm digging into this is because with the traditional approach, an occasional long-lived track won't slow down the simulation much. But as we've discussed, for GPU tracks a single long-lived anomaly can slow down the entire kerne due to load balancing: my fear is that the "worst case" situations will end up causing substantial slowdowns even though they're rare and unimportant. I think @amandalund 's been looking into some of the pathological cases, so we might have a better idea of how much slowdown they cause on GPU.

**Comment by amandalund** [comment]
For reference, this is the distribution of the number of calls to the field stepper per track, per step from the `cms2018+field+msc-vecgeom-gpu` regression problem (with 100k primaries) -- a bit better with this change?
field_stepper_count

**Comment by whokion** [comment]
This plot indeed indicates a serious issue either in the current field driver or in input to the field driver.  It would be good to add a similar plot from Geant4, which, I bet, will show much quicker convergence (or much shorter tail in the distribution. So, we need to categorize those cases in the end tail (including known the energy particles with a long step size) and find a way how to suppress them without sacrificing overall simulation quality.  A 2-dim plot showing step_energy vs. step_length may also be useful to compare between Geant4 and celeritas.

**Pull request closed without merging**
