### PR TITLE
Fix missing positron annihilation process and process diagnostic

### PR DESCRIPTION
**Pull request by amandalund**
Because an `ImportProcess` requires non-empty physics tables to be valid, processes without physics tables (namely, positron annihilation) were not being stored by the `GeantImporter`.  This meant that e.g. in our demo loop there was no annihilation process.

Note that the ROOT files for the tests will also need to be updated -- were we using Geant4 v10 for those?

### CODE REVIEW

**Comment by stognini** [comment]
> were we using Geant4 v10 for those?
`10.7.3` from what I remember. But at this point, it might be useful to move them to `11.0.3` (last tag before we get the grid spacing problem)

**Comment by sethrj** [comment]
Yikes! Good catch. This was a bug introduced with changes specific to `v0.2.0`, right?

I think our ROOT file is using 10.something: I had to regenerate it on my branch and had to update the MSC results consequentially. If you want to update, you can cherry-pick the changes to the unit tests from my `msc-params` branch: d570f97cb3e9c0dfc2d13e1f913d350b66e983a2

**Comment by amandalund** [comment]
@sethrj not sure exactly when it was introduced, though at first glance it looks like positron annihilation was missing from the demo loop since v0.1.1...

**Review by sethrj — APPROVED** [review]
Good catch! 😬 Clearly we need to do more regular verification comparisons against Geant4... though our testing has improved a lot since we did the first comparisons, so (from the changes to the test) we'd definitely catch this bug if it were reintroduced.

**Pull request merged**
