### PR TITLE
Support arbitrary user/internal kernels as part of stepping loop

### LINKED ISSUE #473: Support multiple along-step actions and user-defined actions
One easy way to do this without having a templated pre-step kernel would be to construct a vector mapping particle ID to along-step action ID. This would allow having separate kernels for neutral EM particles, charged EM particles, and even hadronic particles. It would *not* allow mapping within energy ranges (e.g. applying different MSC models based on energy), but we could do something similar to the model selector there.

To support multiple user-inserted actions, I'm adding an enum something like:
```c++
enum class ActionOrdering
{
    pre_physics,
    pre_user,
    along,
    post_physics,
    post_user
};
```
so that we can create the stepper loop simply by sorting explicit actions based on this list.

I think that to support user-enabled actions (and to simplify our initialization code) also should extend `TrackStatus` to have an `born` state during its first step. This would allow us to move some of the initialization of derivative properties (e.g. in the physics state, geomaterial state) to the first place they're used (or in pre-step). Likewise it would let users initialize "private" track states of their own.

---

Currently:
- params have ActionManager
- manager is closely associated with physics, etc. that get created, because
  they register their own actions
- shouldn't add new actions after creating stepper
- high-level app has output control and registers action manager output

To do:
- ActionManager -> ActionRegistry
- registry emits ActionGraph (or for now, ActionSequence): graph (or topological sort) of linearized actions that comprise a step
- This is done in creating a stepper, which owns an actionsequence
- action registry just prints names and descriptions
- sequence stores timing, has sync options, etc.
- add stepper output class

### PR DESCRIPTION
**Pull request by sethrj**
This changes the Stepper to use a "self-ordering" list of actions, which will allow us to add arbitrary user actions as well as multiple along-step kernels. Explicit actions now must supply an `order`, which is essentially a priority number (and the precursor to turning inter-kernel action dependencies into a full DAG). Any actions in the `ActionRegistry` (the "setup" part of the functionality of the former `ActionManager`) will be called as part of the stepper, so adding a user callback to the code is as simple as creating a new action with the `post_post` order and registering it.

I'm not entirely satisfied with where the `ActionSequence` sits (as a detail under stepper) since it's what collects the timing information, and it will likely need to do other things in the future like partitioning threads based on the selected action ID/aliveness.

```c++
//! Within-step ordering of explicit actions
enum class ActionOrder
{
    start,     //!< Initialize tracks
    pre,       //!< Pre-step physics and setup
    along,     //!< Along-step
    pre_post,  //!< Discrete selection kernel
    post,      //!< After step
    post_post, //!< User actions after boundary crossing, collision
    end,       //!< Processing secondaries, including replacing primaries
    size_
};
```

Closes #473

### CODE REVIEW

**Review by amandalund — APPROVED** [review]
This looks great @sethrj! Not sure what's up with the CI, but I didn't see any problems.

**Comment by amandalund** [comment]
Actually I think it's just because the `order_` in `MyExplicitAction` is never set.

**Comment by sethrj** [comment]
Weird that valgrind is crashing... its whole job is to print an "uninitialized memory access". Next time I redo the CI docker image, I'll set up a clang toolchain and enable address sanitizers for celeritas.

**Comment by sethrj** [comment]
Latest CI failure is just a disk space issue. Merging!

**Pull request merged**
