### PR TITLE
Fix Jenkins CI

### PR DESCRIPTION
**Pull request by sethrj**
The [Jenkins CI](https://cloud.cees.ornl.gov/jenkins-ci) is still going haywire. Starting with the last known working jenkins CI commit, see if the CI itself is working, and then update Celeritas.

- New option was required to get clean images for successive stages
- HIP runners right now are broken so I've disabled them for the time being
- Restore `-Wl,--no-as-needed` to jenkins ci run script

### CODE REVIEW

**Comment by sethrj** [comment]
HIP runner is definitely broken
```
[41](https://cloud.cees.ornl.gov/jenkins-ci/job/celeritas/job/PR-1038/1/pipeline-console/?start-byte=0&selected-node=75#log-41)
Caused by: hudson.plugins.git.GitException: Command "git init /var/jenkins/workspace/celeritas/PR-1038" returned status code 128:
[42](https://cloud.cees.ornl.gov/jenkins-ci/job/celeritas/job/PR-1038/1/pipeline-console/?start-byte=0&selected-node=75#log-42)
stdout: 
[43](https://cloud.cees.ornl.gov/jenkins-ci/job/celeritas/job/PR-1038/1/pipeline-console/?start-byte=0&selected-node=75#log-43)
stderr: error: copy-fd: write returned: Disk quota exceeded
[44](https://cloud.cees.ornl.gov/jenkins-ci/job/celeritas/job/PR-1038/1/pipeline-console/?start-byte=0&selected-node=75#log-44)
fatal: cannot copy '/usr/share/git-core/templates/info/exclude' to '/var/jenkins/workspace/celeritas/PR-1038/.git/info/exclude': Disk quota exceeded
[45](https://cloud.cees.ornl.gov/jenkins-ci/job/celeritas/job/PR-1038/1/pipeline-console/?start-byte=0&selected-node=75#log-45)
```

**Comment by sethrj** [comment]
God damn it, it's still not cleaning the docker image when it checks out!!

**Review by pcanal — APPROVED** [review]
LGTM.

**Comment by sethrj** [comment]
@Rombur Would you mind taking a look at the [jenkins file](https://github.com/celeritas-project/celeritas/blob/43a1721c081f7b968bcd9b0bf3983b00b365af01/.jenkins) and the [jenkins build output](https://cloud.cees.ornl.gov/jenkins-ci/job/celeritas/job/PR-1038/lastBuild/console) to see what I could be doing wrong? The build isn't being cleaned at successive stages. :(

From https://issues.jenkins.io/browse/JENKINS-52439:
> So we're not actually copying anything, but we are mounting the workspace from the parent agent into each container. That's normal behavior for Docker in Pipeline.

so how can we get a fresh workspace like one would expect from a VM build? :(

**Comment by Rombur** [comment]
All the other projects just clean up the `build` directory before configuring the project. See for example [here](https://github.com/arborx/ArborX/blob/fbd25845c5406a6108211d762e01d7468f59b4ab/.jenkins/continuous.groovy#L52) Is it a problem to that here?

**Review by pcanal — APPROVED** [review]

**Comment by sethrj** [comment]
Nope, I've added that now... it's just unexpected. I thought the main point of a virtual machine was a reproducible environment, so the change of behavior surprised me. Thanks!

**Pull request merged**
