### PR TITLE
Follow "pass-by-pointer" for mutable reference.

### PR DESCRIPTION
**Pull request by pcanal**
In addition we have 4 categories of exceptions:

* `to/from_json` where the signature is imposed by the `nlohmann` library
* `swap` to match the usual signature from the C++ standard.
* Passing random number generator and engine  to match the usual signature from the C++ standard?

and the potentially updatable:

* make_span ... maybe because taking the address of an array is not easy

```
app/demo-interactor/KNDemoIO.hh:void to_json(nlohmann::json& j, const CudaGridParams& value);
app/demo-interactor/KNDemoIO.hh:void from_json(const nlohmann::json& j, CudaGridParams& value);
app/demo-interactor/KNDemoIO.hh:void to_json(nlohmann::json& j, const KNDemoRunArgs& value);
app/demo-interactor/KNDemoIO.hh:void from_json(const nlohmann::json& j, KNDemoRunArgs& value);
app/demo-interactor/KNDemoIO.hh:void to_json(nlohmann::json& j, const KNDemoResult& value);
app/demo-interactor/KNDemoIO.hh:void from_json(const nlohmann::json& j, KNDemoResult& value);
app/demo-interactor/KNDemoIO.hh:void to_json(nlohmann::json& j, const UniformGridPointers& value);
app/demo-interactor/KNDemoIO.hh:void from_json(const nlohmann::json& j, UniformGridPointers& value);
app/demo-rasterizer/ImageIO.hh:void to_json(nlohmann::json& j, const ImageRunArgs& value);
app/demo-rasterizer/ImageIO.hh:void from_json(const nlohmann::json& j, ImageRunArgs& value);
app/demo-rasterizer/ImageIO.hh:void to_json(nlohmann::json& j, const ImageStore& value);
app/demo-rasterizer/ImageIO.hh:void from_json(const nlohmann::json& j, Array<T, N>& value)
app/demo-rasterizer/ImageIO.hh:void to_json(nlohmann::json& j, const Array<T, N>& value)
```

```
src/base/DeviceVector.hh:    inline void swap(DeviceVector& other) noexcept;
src/base/DeviceVector.hh:inline void swap(DeviceVector<T>&, DeviceVector<T>&) noexcept;
src/base/Quantity.hh:swap(Quantity<U, V>& a, Quantity<U, V>& b) noexcept
src/base/DeviceAllocation.hh:    inline void swap(DeviceAllocation& other) noexcept;
src/base/DeviceAllocation.hh:inline void swap(DeviceAllocation& a, DeviceAllocation& b) noexcept;
```

```
src/random/distributions/RadialDistribution.hh:    inline CELER_FUNCTION result_type operator()(Generator& rng);
src/random/distributions/IsotropicDistribution.hh:    inline CELER_FUNCTION result_type operator()(Generator& rng);
src/random/distributions/ExponentialDistribution.hh:    inline CELER_FUNCTION result_type operator()(Generator& g);
src/random/distributions/GenerateCanonical.hh:inline CELER_FUNCTION RealType generate_canonical(Generator& g);
src/random/distributions/GenerateCanonical.hh:inline CELER_FUNCTION real_type generate_canonical(Generator& g);
src/random/distributions/GenerateCanonical.hh:    result_type operator()(Generator& rng);
src/random/distributions/UniformRealDistribution.hh:    inline CELER_FUNCTION result_type operator()(Generator& rng);
src/random/distributions/BernoulliDistribution.hh:    inline CELER_FUNCTION result_type operator()(Generator& rng);
```

```
src/random/cuda/RngEngine.hh:    inline CELER_FUNCTION result_type operator()(RngEngine& rng);
src/random/cuda/RngEngine.hh:    inline CELER_FUNCTION result_type operator()(RngEngine& rng);
src/physics/material/ElementSelector.hh:    inline CELER_FUNCTION ElementComponentId operator()(Engine& rng) const;
src/physics/em/RayleighInteractor.hh:    inline CELER_FUNCTION Interaction operator()(Engine& rng);
src/physics/em/WentzelInteractor.hh:    inline CELER_FUNCTION Interaction operator()(Engine& rng);
src/physics/em/BetheBlochInteractor.hh:    inline CELER_FUNCTION Interaction operator()(Engine& rng);
src/physics/em/detail/EPlusGGInteractor.hh:    inline CELER_FUNCTION Interaction operator()(Engine& rng);
src/physics/em/MollerBhabhaInteractor.hh:    inline CELER_FUNCTION Interaction operator()(Engine& rng);
src/physics/em/UrbanInteractor.hh:    inline CELER_FUNCTION Interaction operator()(Engine& rng);
src/physics/em/detail/LivermorePEInteractor.hh:    inline CELER_FUNCTION Interaction operator()(Engine& rng);
src/physics/em/detail/LivermorePEInteractor.hh:    inline CELER_FUNCTION Real3 sample_direction(Engine& rng) const;
src/physics/em/detail/KleinNishinaInteractor.hh:    inline CELER_FUNCTION Interaction operator()(Engine& rng);
src/physics/em/detail/BetheHeitlerInteractor.hh:    inline CELER_FUNCTION Interaction operator()(Engine& rng);
src/physics/em/BremRelInteractor.hh:    inline CELER_FUNCTION Interaction operator()(Engine& rng);
src/base/StackAllocatorView.hh:    Interaction operator()(Engine&)
```

```
src/base/Span.hh:CELER_CONSTEXPR_FUNCTION Span<T, N> make_span(Array<T, N>& x)
src/base/Span.hh:CELER_FUNCTION Span<typename T::value_type> make_span(T& cont)
src/base/detail/SpanImpl.hh:    SpanImpl(const SpanImpl<T, dynamic_extent>& other) : data(other.data)
```

### CODE REVIEW

**Review by sethrj — APPROVED** [review]
Thanks @pcanal for fixing the inconsistencies!

**Comment by pcanal** [comment]
@sethrj Should make_span be updated too?

**Comment by sethrj** [comment]
@pcanal Like the other exceptions you mentioned, `make_span` is based on an existing library use pattern -- the `gsl::span` has it to support pre-C++17 builds. I think in this case it's better to match the const-reference use case.

**Comment by sethrj** [comment]
See discussion https://github.com/celeritas-project/celeritas/pull/128#discussion_r567479939 .

**Pull request merged**
