### PR TITLE
Add post-kernel-launch assertions

### PR DESCRIPTION
**Pull request by pcanal**

### CODE REVIEW

**Comment by mrguilima** [comment]
Curious to know the reasoning behind this reordering of includes.

**Comment by pcanal** [comment]
@sethrj Is there a way to customize the CI build for this run?  In the default settings the test "app/demo-rasterizer" is not run. (It needs CELERITAS_USE_VecGeom enabled).

**Comment by pcanal** [comment]
> Curious to know the reasoning behind this reordering of includes.

This is unrelated to this PR.  It is already in the master via: https://github.com/celeritas-project/celeritas/pull/118
where you can find how this is a work-around an nvling bug (present in cuda 10 and fixed in cuda 11).

**Comment by amandalund** [comment]
@pcanal isn't it run in the cuda-11 build?

**Comment by pcanal** [comment]
> isn't it run in the cuda-11 build?

Indeed it is. I missed that there was 2 builds.  So on wc.fnal.gov+cuda10 it fails in the CI with cuda11 it works.  I will try locally with cuda 11.

**Comment by sethrj** [comment]
@pcanal Looks like something got mangled pretty badly in the title, can you fix it? It looks like this is just adding the call to check for a launch error? Would you be up for checking the other places in the code where we launch kernels, and make sure they also have the error peeking?

**Comment by pcanal** [comment]
> Would you be up for checking the other places in the code where we launch kernels, and make sure they also have the error peeking?

Sure ...  But first I want to try to understand why this kernel fails on wc.fnal.gov with both cuda 10 and 11 and works fine on the CI with cuda 11.

**Comment by sethrj** [comment]
Ahh I get it now.

**Comment by pcanal** [comment]
Note: it seems to use to work .. so bisecting now.

**Comment by pcanal** [comment]
It seems that the first commit when it failed is c63c3298032db403cddee0043d42da12b8964203

**Comment by sethrj** [comment]
> It seems that the first commit when it failed is [c63c329](https://github.com/celeritas-project/celeritas/commit/c63c3298032db403cddee0043d42da12b8964203).
> I still need to figure out 'why' this is ...

Uh oh. The thing that stands out to me is adding separable compilation to the main library.

**Comment by pcanal** [comment]
I agree ... (the build fails without it though) ... One odd part is "why" does it work on some machine (the CI, probably yours) and not mine ...

**Comment by sethrj** [comment]
@pcanal Would you be up for changing this PR to add the requisite post-kernel-launch check to any other relevant locations? The need for that extra check was a good catch -- it was a bad assumption on my end that the device synchronize call would error if there had been a problem.

**Comment by pcanal** [comment]
> Would you be up for changing this PR to add the requisite post-kernel-launch check to any other relevant locations? 

Yes, I will review and update the existing kernel launch to make sure the error are tested.

**Review by sethrj — APPROVED** [review]
Looks good, thanks @pcanal !

**Pull request merged**
