### PR TITLE
Refactor vecgeom setup in preparation for surface support

### PR DESCRIPTION
**Pull request by sethrj**
Prerequisite to #1016 . This adds a helper class to simplify the limit save/restore, adds a simple CMS test, moves the vecgeom verbosity function to a static free function for reuse, and adds a function to check for the vecgeom build type.

### CODE REVIEW

**Review by mrguilima — CHANGES_REQUESTED** [review]
I've some suggested changes to fix the new Vecgeom:SimpleCms* test, see branch `vg-pre-surf-refact` in my fork, see https://github.com/mrguilima/celeritas/tree/vg-pre-surf-refact

**Comment by sethrj** [comment]
@mrguilima, your last patch https://github.com/mrguilima/celeritas/commit/daf58e3cae3f149d10a35929c1ddc823930a95ed isn't a problem with this PR. It's an extra thing for vecgeom v2 and would probably belong better on your branch, which is actually about supporting the newer vecgeom. This PR is *just* about laying the groundwork for it and adding tests that are known to work on v1.

**Comment by mrguilima** [comment]
Ok regarding v1.x and ignoring v2.x for now.
In my local tests, there are two failing tests, trackSort with VecGeom enabled (see issue #979) and celer-g4:cpu.
Do they pass in your local tests?
Otherwise, LGTM.
Thanks!

**Review by mrguilima — APPROVED** [review]
LGTM

**Pull request merged**
