### PR TITLE
Fix Geant4 field construction in celer-g4

### PR DESCRIPTION
**Pull request by amandalund**
This fixes two issues with the field in the celer-g4 app:

- The field in Geant4 was not being constructed if no SDs were present.
- It looks like having a zero-strength field is not the same thing as having no field in Geant4 (I think the field propagator will still be used in the former case). Previously we were constructing the `G4MagneticField` even if the field magnitude was zero.

### CODE REVIEW

**Review by sethrj — APPROVED** [review]
Nice catch @amandalund ! Is it correct then that our calculated speedup for "no magnetic field" will be worse (before, we were comparing celeritas linear propagator with geant4 field propagator), but our relative performance will be much better for the "no SD" case (because previously Geant4 had no magnetic field at all)?

**Comment by amandalund** [comment]
Yep, that's what I'd expect.

**Comment by sethrj** [comment]
I hope @whokion hasn't completed his rerun yet 😉

**Comment by whokion** [comment]
@amandalund, @sethrj Sorry that I did not see/review this MR. 

> This fixes two issues with the field in the celer-g4 app:

I do not think that this change will affect anything as the zero-field equivalence in Geant4 is based on the filed manager ptr, not on a magnetic field ptr.
 
>     * The field in Geant4 was not being constructed if no SDs were present.

Field and SD are two independent things (even though they can be added separately inside the common interface), so I do not understand this statement.

>     * It looks like having a zero-strength field is not the same thing as having no field in Geant4 (I think the field propagator will still be used in the former case). Previously we were constructing the `G4MagneticField` even if the field magnitude was zero.

I thought that both celeritas and geant4 use the field propagator if the field type is uniform and the field strength is zero, so we are still comparing equivalent works for performance.  If we want to force not to use the field at all for the zero-field case, then we need to introduce field_type="none" or "no_field" explicitly.

**Comment by amandalund** [comment]
> Field and SD are two independent things (even though they can be added separately inside the common interface), so I do not understand this statement.

@whokion the problem was we were returning immediately in `DetectorConstruction::ConstructSDandField()` if there were no SDs, and since the field was constructed at the end of the method it was skipped.

> I thought that both celeritas and geant4 use the field propagator if the field type is uniform and the field strength is zero, so we are still comparing equivalent works for performance.

[Celeritas](https://github.com/celeritas-project/celeritas/blob/2780ceaa7a68c0bb3729137f04f462ba55c54cfc/src/accel/AlongStepFactory.cc#L70) will use a linear propagator if the field strength is zero, while it looks to me like the [Geant4](https://gitlab.cern.ch/geant4/geant4/-/blob/master/source/processes/transportation/src/G4Transportation.cc#L260) transportation process checks if the `G4Field` pointer is null (rather than checking if the field strength is zero) and if not uses the field propagator.

**Comment by whokion** [comment]
Okay,  it was a definitely bug (did not compare old/new codes).  For the second bullet, I did not know that celeritas uses the linear propagator when the field strength is zero - can you point where we do this in the along step action?

**Comment by sethrj** [comment]
@whokion Yep it's done in the `accel` front end code: see https://github.com/celeritas-project/celeritas/blob/2780ceaa7a68c0bb3729137f04f462ba55c54cfc/src/accel/AlongStepFactory.cc#L70-L80

**Pull request merged**
