### PR TITLE
Fix sampling of secondary gamma energies in EPlusGGInteractor

### PR DESCRIPTION
**Pull request by whokion**
This MR fixes a bug in sampling secondary gamma energies in `EPlusGGInteractor`, using the composition and rejection in which BernoulliDistribution(p) is used instead of BernoulliDistribution(1-p) where the rejection function, p is highly skewed, and addresses the difference seen in physics verification with respect to Geant4 reported by @mrguilima.

### CODE REVIEW

**Review by sethrj — APPROVED** [review]
Looks great. I'll wait for @mrguilima to check that this fixes the distribution.

**Comment by mrguilima** [comment]
Perfect agreement in the secondary energy distribution.
Thanks, Soon!

**Review by mrguilima — APPROVED** [review]
LGTM

**Comment by mrguilima** [comment]
[canvas_energy-10gev.pdf](https://github.com/celeritas-project/celeritas/files/12323902/canvas_energy-10gev.pdf)

**Comment by whokion** [comment]
Thank you for the prompt verification.  I will resolve the remaining failures due to this update.

**Review by sethrj — APPROVED** [review]

**Pull request merged**
