### PR TITLE
Add element selection sampler

### PR DESCRIPTION
**Pull request by sethrj**
This adds a helper class that is a composition/template-based equivalent to `G4VEmModel::SelectRandomAtom`. Its constructor accepts a function for calculating the microscopic cross section, and its call operator samples an element ID using the given random number generator.

See https://github.com/celeritas-project/cuda-test-snippets/blob/master/select-element/README.md.

See #60.

### CODE REVIEW

**Review by vpascuzz — APPROVED** [review]

**Comment by vpascuzz** [comment]
Looks good! Only minor comment is using `el` to refer to elemental variables, however, I do note that since I refer to material classes, this is not so confusing and, based on the context, is understandable enough.
https://google.github.io/styleguide/cppguide.html#General_Naming_Rules

**Comment by sethrj** [comment]
@vpascuzz Thanks! Do you think `elem` or `element` would make the implementation more readable than `el`? I tend to use shortened variable names for local/private quantities for brevity (and I think `el` where I used it is pretty local) but am happy to change as needed.

**Comment by vpascuzz** [comment]
@sethrj `element` is nice, but I'm not going to lose any sleep if we use `elem` or just keep `el`. Again, I think it's obvious enough from the context, and the comments help. :)

**Comment by sethrj** [comment]
OK @vpascuzz , I updated the private `el_` and `mat_` to `elemental_` and `material_` as appropriate.

**Pull request merged**
