### PR TITLE
Fix link errors in edge cases and restore HIP testing

### PR DESCRIPTION
**Pull request by sethrj**
#1038 had to disable HIP to get jenkins working because of problems with the runners. This:
- restores the HIP runtime execution
- adds a warning about the inability to link to *static* celeritas built against HIP (I think due to a downstream cmake bug)
- fixes linking a non-CUDA Celeritas against a CUDA-enabled VecGeom (@hhollenb )

### CODE REVIEW

**Comment by sethrj** [comment]
@Rombur would you mind pinging me here or on Teams when the ROCm runners are fixed? It's not urgent. Thanks for getting the CUDA runners back online!

([Current failing HIP build](https://cloud.cees.ornl.gov/jenkins-ci/job/celeritas/job/PR-1042/1/pipeline-console/?selected-node=12))

**Comment by Rombur** [comment]
Sure

**Comment by sethrj** [comment]
Still broken...

**Comment by Rombur** [comment]
The AMD machines are back online

**Review by amandalund — APPROVED** [review]
Thanks @sethrj!

**Pull request merged**
