### PR TITLE
Docker: add ubuntu 18 script and no-debug testing

### PR DESCRIPTION
**Pull request by sethrj**
- Switch to Docker+CEES rather than Travis for Ubuntu 18 (including GCC7, which is currently failing due to a compiler bug)
- Work around the GCC7 compiler bug
- Add a test configuration with CELERITAS_DEBUG=OFF

### CODE REVIEW

**Comment by pcanal** [comment]
Because we do squash on merge, should we put the commit "7a15ea28292d77f80dc6c1272  Fix GCC7" in its own PR otherwise those changes will be somewhat hidden in a larger unrelated commit?

**Comment by sethrj** [comment]
> Because we do squash on merge, should we put the commit "7a15ea28292d77f80dc6c1272 Fix GCC7" in its own PR otherwise those changes will be somewhat hidden in a larger unrelated commit?

The motivation for the docker changes was to set up an environment where I could test and fix the GCC7 error (which Jeff Larkin encountered and which is causing the only-on-master travis build to fail), so the change sets are closely related. Maybe I should retitle to make the GCC7 fix the point of the MR, with changes to the CI rolled in?

**Comment by pcanal** [comment]
It's up to you but personally I see the CI and the code change has 2 different things.  In this particular case, I would go for the simplest solution, namely a merge without squash :)

**Review by pcanal — APPROVED** [review]

**Comment by sethrj** [comment]
I'm digging the linear history ;) but beside that, I can't commit the new CI stuff without working around the GCC7 error, and I can't figure out how to work around the GCC7 error without the new CI stuff. I think that makes a good argument for a single atomic commit.

**Pull request merged**
