### PR TITLE
Fix field propagator at boundary crossings

### PR DESCRIPTION
**Pull request by sethrj**
Based on the discussion we had today, it's possible to miss a tangent boundary if the intersection point is less than the chord tolerance. I've updated the test so that one track goes beyond the boundary by less than the chord tolerance (it barely ignores the surface) and the second by greater than the tolerance (it definitely hits it but at a grazing angle). Both tests now pass.

-----------

This is a work-in-progress commit where I'm narrowing down a potential failure in solving the intersection point with a single surface along a curved path with the field propagator. There are two slight variations on the same test in which the track barely leaves the current volume, traveling left at the point {0,5,0} along a curve of unit radius. The first variation starts the particle at $y=4 + 1.1 \Delta_\textrm{chord}$, which should definitely intersect the surface; and the second starts at $y=4 + 0.9 \Delta_\textrm{chord}$ which probably should not (and in practice does not). In this test the field driver has a delta chord tolerance of 0.025 cm.

# Initial behavior

The output values are at each step in the main propagation loop:
```
        cout << "- advance(" << remaining << ", " << state_.pos << ") -> {"
             << substep.step << ", " << substep.state.pos << "}" << endl;
```

## Intersects boundary (fail)

```
- advance(6.28319, {1,4.0275,0}) -> {0.448159, {0.901247,4.46081,0}}
 + chord length 0.444418 => linear step 0.444418
 + advancing to substep end point
- advance(5.83503, {0.901247,4.46081,0}) -> {0.448157, {0.624492,4.80853,0}}
 + chord length 0.444416 => linear step 0.444416
 + advancing to substep end point
- advance(5.38687, {0.624492,4.80853,0}) -> {0.448155, {0.224399,5.002,0}}
 + chord length 0.444414 => linear step 0.439825 (boundary!)
 + Setting remaining distance to a fraction 0.989673 of the substep
- advance(0.443527, {0.624492,4.80853,0}) -> {0.443527, {0.228906,5.00095,0}}
 + chord length 0.439901 => linear step 0.437732 (boundary!)
 + Setting remaining distance to a fraction 0.995069 of the substep
- advance(0.44134, {0.624492,4.80853,0}) -> {0.44134, {0.231035,5.00045,0}}
 + chord length 0.437767 => linear step 0.43675 (boundary!)
 + Setting remaining distance to a fraction 0.997677 of the substep
- advance(0.440315, {0.624492,4.80853,0}) -> {0.440315, {0.232032,5.00021,0}}
 + chord length 0.436767 => linear step 0.436292 (boundary!)
 + Setting remaining distance to a fraction 0.998912 of the substep
- advance(0.439836, {0.624492,4.80853,0}) -> {0.439836, {0.232498,5.0001,0}}
 + chord length 0.436299 => linear step 0.436078 (boundary!)
 + Setting remaining distance to a fraction 0.999492 of the substep
- advance(0.439613, {0.624492,4.80853,0}) -> {0.439613, {0.232715,5.00005,0}}
 + chord length 0.436081 => linear step 0.435978 (boundary!)
 + Setting remaining distance to a fraction 0.999763 of the substep
- advance(0.439509, {0.624492,4.80853,0}) -> {0.439509, {0.232816,5.00002,0}}
 + chord length 0.43598 => linear step 0.435932 (boundary!)
 + Setting remaining distance to a fraction 0.99989 of the substep
- advance(0.43946, {0.624492,4.80853,0}) -> {0.43946, {0.232863,5.00001,0}}
 + chord length 0.435933 => linear step 0.43591 (boundary!)
 + Setting remaining distance to a fraction 0.999949 of the substep
- advance(0.439438, {0.624492,4.80853,0}) -> {0.439438, {0.232885,5,0}}
 + chord length 0.435911 => linear step 0.4359 (boundary!)
 + Setting remaining distance to a fraction 0.999976 of the substep
- advance(0.439427, {0.624492,4.80853,0}) -> {0.439427, {0.232896,5,0}}
 + chord length 0.4359 => linear step 0.435896 (boundary!)
 + intercept is sufficiently close to substep point 1e-06
- Moved to boundary at position {0.2329,5,0}
```
failure messages:
```
/Users/seth/.local/src/celeritas/test/celeritas/field/FieldPropagator.test.cc:444: Failure
Value of: result.distance
  Actual: 1.3357430026561443
Expected: circ / 4
Which is: 1.5707963267948966
(Relative error -0.14963959370745578 exceeds tolerance 0.025000000000000001)
Google Test trace:
/Users/seth/.local/src/celeritas/test/celeritas/field/FieldPropagator.test.cc:435: Barely hits boundary
/Users/seth/.local/src/celeritas/test/celeritas/field/FieldPropagator.test.cc:446: Failure
Expected: (distance(Real3({1, 5, 0}), geo.pos())) < (1e-5), actual: 0.7671 vs 1e-05
Actually stopped at {0.2328998819190623,5,0}
Google Test trace:
/Users/seth/.local/src/celeritas/test/celeritas/field/FieldPropagator.test.cc:435: Barely hits boundary
/Users/seth/.local/src/celeritas/test/celeritas/field/FieldPropagator.test.cc:448: Failure
Expected: (distance(Real3({-1, 0, 0}), geo.dir())) < (1e-5), actual: 0.234513 vs 1e-05
Ending direction at {-0.97250177989559339,0.23289544456666161,0}
Google Test trace:
/Users/seth/.local/src/celeritas/test/celeritas/field/FieldPropagator.test.cc:435: Barely hits boundary
```

## Misses boundary

```
Propagate up to 6.28319
- advance(6.28319, {1,4.0225,0}) -> {0.448159, {0.901247,4.45581,0}}
 + chord length 0.444418 => linear step 0.444418
 + advancing to substep end point
- advance(5.83503, {0.901247,4.45581,0}) -> {0.448157, {0.624492,4.80353,0}}
 + chord length 0.444416 => linear step 0.444416
 + advancing to substep end point
- advance(5.38687, {0.624492,4.80353,0}) -> {0.448155, {0.224399,4.997,0}}
 + chord length 0.444414 => linear step 0.444414
 + advancing to substep end point
- advance(4.93871, {0.224399,4.997,0}) -> {0.448154, {-0.220013,4.998,0}}
 + chord length 0.444413 => linear step 0.444413
 + advancing to substep end point
(etc...)
```

### CODE REVIEW

**Comment by sethrj** [comment]
Actually this might be right: I think the fact that `{0.97, 0.25...}` is a correctly normalized unit vector threw me off.

**Review by whokion — APPROVED** [review]
This update for the field test, `electron_tangent_cross` is fine for now, but not actually resolve the issue of skipping the boundary crossing when the ending position of a sub-step (advanced by the given error condition) returns to the same volume of the start position of the sub-step (even though the resultant curved trajectory actually crosses the boundary).  As you clearly state that this is a part of WIP toward a real fix, at the conversation, but we may also keep the previous test case too, which clearly demonstrates a failed case.

**Comment by sethrj** [comment]
@whokion I think this demonstrates that, at least in one simple scenario, it behaves as expected, rather than in error as I originally thought. The field driver correctly limits the curved path based on the "miss distance" (`delta_chord`). The field propagator now has two tests, both of which behave as expected:
1. The track dips into another volume by greater than the miss distance, so one of the substeps ends slightly in the new volume so the propagator correctly finds the intersection point along the curve.
2. A second track dips into another volume by *less* than the miss distance, and it happens that although the curved path calculated by the substepper goes outside the volume, both the start and end points are inside the volume. This causes the propagator to miss the boundary, but the distance to the furthest point along the curve is still less than the miss distance. It's not ideal, but it's acceptable given the provided driver tolerances.

I've also added a handful of extra tests for propagation near corners, and all of those cases behave reasonably as well.

**Review by whokion — APPROVED** [review]
Okay. Very good! - I misunderstood the second test.  Thank you for all additional tests!
Good to go.

**Pull request merged**
