### PR TITLE
Define CUDA assertion that still fails when NDEBUG

### PR DESCRIPTION
**Pull request by sethrj**
I realized while profiling #312 that the Celeritas assertion macros (which use CUDA `assert` under the hood) were being completely elided when building `-DCELERITAS_DEBUG=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo` because the build type adds `NDEBUG` to the CUDA flags, which disables `assert`. This PR changes the macros so that the assertion condition is still checked when asking for `DEBUG` mode, although of course we won't get a clean error message.

cc @sphamil @tmdelellis for Shift

### CODE REVIEW

**Comment by sethrj** [comment]
Even though the CI pipeline didn't run (will have to get with @dalg24 on my return) I've tested the debug, ndebug, and minimal builds on emmet.

**Comment by dalg24** [comment]
The Jenkins server had run out of disk space.  You can go ahead and re-trigger the build.

**Review by pcanal — APPROVED** [review]

**Comment by sethrj** [comment]
Thanks @dalg24 !

**Comment by sethrj** [comment]
I tested the "DNDEBUG" assertion mechanism before building... and it's pretty ugly:
```
C++ exception with description "../test/base/NumericLimits.test.cu:62:
celeritas: cuda error: unspecified launch failure
    cudaDeviceSynchronize()" thrown in the test body.
```
on the V100 (arch 70), and
```
unknown file: Failure
C++ exception with description "/home/s3j/.local/src/celeritas/test/base/NumericLimits.test.cu:62:
celeritas: cuda error: an illegal instruction was encountered
    cudaDeviceSynchronize()" thrown in the test body.
```
on the older one on emmet (arch 35).

But I guess this is still better than ignoring the assertion completely and giving surprising timing results by optimizing away the checks.

**Pull request merged**
