### PR TITLE
Add Mermaid CSG tree output

### PR DESCRIPTION
**Pull request by sethrj**
This updates the `orange-csg-to-dot.py` script to output Mermaid plots for the CSG tree.
Example:
```console
$ ./test/orange/orangeinp_UnitProto --gtest_filter=InputBuilderTest.hierarchy >/dev/null
status: Constructing ORANGE surfaces and runtime data
info: Wrote ORANGE protos to inputbuilder-hierarchy.protos.json
info: Wrote ORANGE debug info to inputbuilder-hierarchy.csg.json
$ ../scripts/user/orange-csg-to-dot.py -u 0 inputbuilder-hierarchy.csg.json | pbcopy
```
results in this mermaid chart (copied to the clipboard)
```mermaid
flowchart TB
  n00["t"]
  n01["~"]
  n01 --> n00
  n02["[EXTERIOR]\nbound@s"]
  n03["bound\n~"]
  n03 --> n02
  n04["d1:ext@s"]
  n05["d1:ext\n~"]
  n05 --> n04
  n06["d2:ext@s"]
  n07["d2:ext\n~"]
  n07 --> n06
  n08["bound@s"]
  n09["bound\n~"]
  n09 --> n08
  n10["bound@mz"]
  n11["bound@pz"]
  n12["~"]
  n12 --> n11
  n13["bound@cz"]
  n14["~"]
  n14 --> n13
  n15["bound\n&"]
  n15 --> n10
  n15 --> n12
  n15 --> n14
  n16["leaf1@s"]
  n17["leaf1\n~"]
  n17 --> n16
  n18["~"]
  n18 --> n15
  n19["interior\n&"]
  n19 --> n03
  n19 --> n04
  n19 --> n06
  n19 --> n08
  n19 --> n16
  n19 --> n18
subgraph Volumes
  v02(["[EXTERIOR]@global"])
  v05(["d1@global"])
  v07(["d2@global"])
  v09(["filled_daughter@global"])
  v15(["leafy@global"])
  v17(["leaf1"])
  v19(["interior"])
end
  v02 <--> n02
  v05 <--> n05
  v07 <--> n07
  v09 <--> n09
  v15 <--> n15
  v17 <--> n17
  v19 <--> n19
```

To export a `.csg.json` file from a GDML, run:
```console
$ GDML=filename.gdml  ./test/orange/g4org_Converter --gtest_filter=ConverterTest.DISABLED_arbitrary --gtest_also_run_disabled_tests > /dev/null
```
(I should probably make this a little helper executable or extend the `orange-update` app.)

From inside a unit test, include `orange/orangeinp/CsgTestUtils.hh` and call `to_json_string(my_tree)`. Then you can copy the output and run `pbpaste | scripts/user/orange-csg-to-dot.py - | pbcopy` to turn the clipboard into a mermaid plot :)

### CODE REVIEW

**Comment by sethrj** [comment]
graphviz output for u0

**Comment by sethrj** [comment]
@esseivaju For #1289  you can write your CSG trees to JSON and load them into this script to visualize them.

**Review by esseivaju — APPROVED** [review]
Nice! Is there an utility class to dump a `CsgTree` to json?

**Comment by sethrj** [comment]
@esseivaju To export a `.csg.json` file from a GDML, run:
```console
$ GDML=filename.gdml  ./test/orange/g4org_Converter --gtest_filter=ConverterTest.DISABLED_arbitrary --gtest_also_run_disabled_tests > /dev/null
```
(I should probably make this a little helper executable or extend the `orange-update` app.)

From inside a unit test, include `orange/orangeinp/CsgTestUtils.hh` and call `to_json_string(my_tree)`. Then you can copy the output and run `pbpaste | scripts/user/orange-csg-to-dot.py - | pbcopy` to turn the clipboard into a mermaid plot :)

**Pull request merged**
