### PR TITLE
Support for Summit

### PR DESCRIPTION
**Pull request by sethrj**
- Add summit build script/environment (and automatically load env when running `build.sh`) 
- Wrap Geant4 run manager initializer in ScopedRedirect to avoid corrupting JSON stdout
- Fix a couple of warnings that show up on GCC

### CODE REVIEW

**Review by amandalund — APPROVED** [review]
Looks good @sethrj!

**Comment by sethrj** [comment]
Thanks @amandalund! And ironically, the time to load Geant4 and generate the cross sections inline seems to be shorter than the time needed to load ROOT and all its shared libraries... :(

**Comment by pcanal** [comment]
That is a bit surprising :) .. and the number of libraries should apriori be not that high (libCore, libRIO, libTree, libNet, libImt and libCling).  For example, on my node: I get:
```
time root.exe -l -b -q -e 'gSystem->Load("libTree")'
real    0m0.183s
user    0m0.117s
sys     0m0.040s
```

**Comment by pcanal** [comment]
>  (0.37s to merely call the TOpen command,

Since the files are local, the following should work and be faster:
```
TFile *file = new TFile(filename, "READ");
```

**Comment by sethrj** [comment]
@pcanal What's it trying to do now? 😕 I'll make the change and see...

**Comment by sethrj** [comment]
No change from `"recreate"` to `"RECREATE"` for the exporter (still 0.36s) nor from `"read"` to `"READ"` (still 0.43 s).

**Comment by pcanal** [comment]
The change I was hinting at is not about the casing of the argument but rather to switch from:
```
TFile::Open(filename, openingmode);
```
to
```
new TFile(filename, openiningmode);
```
The former supports remote protocols (eg `http://where.com/filename.root') and do so by invoking a factory function which uses the interpreter to indirectly call the right constructor (different protocol are implemented using a series of classes derived from `TFIle`).  It is plausible that some of the time is spent in setup of the interpreter and factory functions.

**Comment by sethrj** [comment]
Ah, ok. No, there was no change in timing. For what it's worth, the ROOT loading runs substantially slower in a debugger; so much so that it's easy to interrupt: here's a sample of what I see:
```
info: Opening ROOT file at simple-cms-gpu.root
Process 2053068 stopped and restarted: thread 1 received signal: SIGCHLD
Process 2053068 stopped and restarted: thread 1 received signal: SIGCHLD
Process 2053068 stopped and restarted: thread 1 received signal: SIGCHLD
Process 2053068 stopped and restarted: thread 1 received signal: SIGCHLD
Process 2053068 stopped and restarted: thread 1 received signal: SIGCHLD
Process 2053068 stopped and restarted: thread 1 received signal: SIGCHLD
Process 2053068 stopped
* thread #1, name = 'demo-loop', stop reason = signal SIGSTOP
    frame #0: 0x00007ffff55d5635 libc.so.6`__strstr_sse2_unaligned + 165
libc.so.6`__strstr_sse2_unaligned:
->  0x7ffff55d5635 <+165>: orq    %rax, %r8
    0x7ffff55d5638 <+168>: je     0x7ffff55d56a0            ; <+272>
    0x7ffff55d563a <+170>: bsfq   %r8, %rax
    0x7ffff55d563e <+174>: addq   %rdi, %rax
(lldb) bt
* thread #1, name = 'demo-loop', stop reason = signal SIGSTOP
  * frame #0: 0x00007ffff55d5635 libc.so.6`__strstr_sse2_unaligned + 165
    frame #1: 0x00007ffff123e104 libCore.so.6.24`TEnvRec::ExpandValue(char const*) [inlined] strstr(__needle=<unavailable>, __haystack=<unavailable>) at string.h:319:27
    frame #2: 0x00007ffff123e0fc libCore.so.6.24`TEnvRec::ExpandValue(this=0x000000000316a880, value="libGui.so ") at TEnv.cxx:342:30
    frame #3: 0x00007ffff123e2d6 libCore.so.6.24`TEnvRec::TEnvRec(this=0x000000000316a880, n=<unavailable>, v="@1j\xf1\xff\U0000007f", t=<unavailable>, l=kEnvChange) at TEnv.cxx:277:24
```

**Comment by sethrj** [comment]
@pcanal ROOT is calling fork/popen somewhere... which is probably part of the slowdown.

**Comment by pcanal** [comment]
GetSystemLibraryPaths:popen: Apparently Cling calls 'ls' to gather the list of available system library 

TEnvRec: this is the parsing of the resource file and in particular the replacement of "variables" used there ...

**Comment by sethrj** [comment]
ROOT is just a very heavyweight dependency for what we need right now… and it doesn't seem to follow the "pay for what you use" philosophy of C++. Not a big deal currently (it's half a second after all) and we've got a plan for IO when we run at massively parallel scale.

**Pull request merged**
