### PR TITLE
Use CutoffView in atomic relaxation

### PR DESCRIPTION
**Pull request by amandalund**
Now that we have production cuts, use `CutoffView` to get the electron and photon energy cutoffs for atomic relaxation. I made a minor change to the `CutoffView` interface so it now constructs the view with the material ID and accepts the particle ID as an argument in the `energy()` and `range()` methods -- this way we don't have to construct a separate view for each particle type. I also moved the structs for the raw imported EADL transition data from the `AtomicRelaxationParams` class to the io/ directory.

Right now on emmet I'm getting the same nvlink error that we saw in #118,
```
nvlink error   : Size doesn't match for '_ZN9celeritas9SecondaryC1Ev$146' in 'src/CMakeFiles/celeritas.dir/physics/em/detail/MollerBhabha.cu.o', first specified in 'src/CMakeFiles/celeritas.dir/physics/em/detail/BetheHeitler.cu.o'
nvlink fatal   : merge_elf failed
```
which I don't have a workaround for yet.

### CODE REVIEW

**Review by sethrj — APPROVED** [review]
Perfect! 💯

**Comment by amandalund** [comment]
Well, removing an assertion seemed to get rid of the nvlink error... I have no idea why or if there's a better way around it :(.

**Review by stognini — APPROVED** [review]
Great job. :)

**Comment by sethrj** [comment]
The ci passed so I assume you're talking about a build on Emmet? Another mystery CUDA 10 error... thanks and merging!

**Comment by amandalund** [comment]
Correct, on emmet. thanks!

**Comment by sethrj** [comment]
> Correct, on emmet (see above). thanks!

Right, duh, missed that. And I had my finger on the merge button but got distracted! Sorry! Merged now.

**Pull request merged**
