### PR TITLE
Insert SortTrackAction when sorting by particle type

### PR DESCRIPTION
**Pull request by esseivaju**
I didn't update the switch statement which is inserting the SortTracksAction in #1044. 

Also refactoring CoreState to only have the necessary thread_offsets_ collection, moving all the template code to the internal state struct `CoreStateThreadOffsets`.

### CODE REVIEW

**Comment by sethrj** [comment]
Changing the "default" to spelling out the remaining options would be safer since clang will catch the omission.

**Comment by esseivaju** [comment]
yes, I was considering doing that (or using pragma diagnostic switch-enum?) but given that we do a switch on that enum in many places and it's not likely to get updated often, I ended up leaving the default. Maybe just doing it in accel is fine since it's not closely related to SortTracksAction you're more likely to forget it here.

**Comment by sethrj** [comment]
For some reason github isn't letting me code review. Two comments:

1. Can you add a super small test to TrackSort.test.cc that fails before the fix and passes after? (maybe we need something more "manual" than running a whole tracking loop? i.e. something to fill up some bogus states and just launch the action)
2. Does `is_sort_by_action` in SortTracksAction.cc also need to be updated? If so maybe it needs to be rephrased by negating the enums that *don't* need sorting.

**Comment by esseivaju** [comment]
> 1. Can you add a super small test to TrackSort.test.cc that fails before the fix and passes after? (maybe we need something more "manual" than running a whole tracking loop? i.e. something to fill up some bogus states and just launch the action)

Mmh, how would you test that? You have to instantiate `CoreParams` and check that it is in the expected state given its input. Wouldn't that fit better in a dedicated `CoreParams` unit test?

> 2. Does `is_sort_by_action` in SortTracksAction.cc also need to be updated? If so maybe it needs to be rephrased by negating the enums that _don't_ need sorting.

This doesn't need to be updated. This is used when sorting on a key that would allow to launch a kernel with a reduced grid size. This is not the case for particle_type.

**Comment by sethrj** [comment]
TrackSort.test.cc already does create core instances. You could manually call the initialize track action to set a bunch of primaries, then just manually call the sort action, then check that the order is correct?

**Review by sethrj — APPROVED** [review]
Nice improvement. Thanks for figuring out a way to add the tests!

**Pull request merged**
