### PR TITLE
Support ROOT IO for celer-g4 SD output

### PR DESCRIPTION
**Pull request by pcanal**

### CODE REVIEW

**Comment by stognini** [comment]
Just tried to build this locally (on macOS, not Linux), and besides a couple basic errors that I address in #950, I also hit this one:

```
[496/497] Linking CXX shared library lib/libceler-g4-io.dylib
FAILED: lib/libceler-g4-io.dylib 
: && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -Wall -Wextra -pedantic -fcolor-diagnostics -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -mmacosx-version-min=12.6 -dynamiclib -Wl,-headerpad_max_install_names -L/usr/local/opt/qt@5/lib   -L/Users/Shared/ornldev/code/spack/opt/spack/darwin-monterey-skylake/apple-clang-14.0.0/hwloc-2.9.1-vbhj7boo2gdj3h73a34dvvx7axzenhy6/lib -L/Users/Shared/ornldev/code/spack/opt/spack/darwin-monterey-skylake/apple-clang-14.0.0/libevent-2.1.12-tzkcxwonksly7i2r2q5hn72wxvq2345c/lib -L/Users/Shared/ornldev/code/spack/opt/spack/darwin-monterey-skylake/apple-clang-14.0.0/pmix-4.2.3-766a46zvts22uulmbkawo4jx4rzvd3bi/lib -o lib/libceler-g4-io.dylib -install_name @rpath/libceler-g4-io.dylib app/celer-g4/CMakeFiles/celer-g4-io.dir/HitClassesRootInterfaces.cxx.o app/celer-g4/CMakeFiles/celer-g4-io.dir/HitRootIO.cc.o -F/usr/local/opt/qt@5/lib -Wl,-rpath,/Users/4s2/celeritas-project/celeritas/build/lib -Wl,-rpath,/Users/4s2/programs/root/install/lib -Wl,-rpath,/Users/Shared/ornldev/code/spack/opt/spack/darwin-monterey-skylake/apple-clang-14.0.0/vecgeom-1.2.3-orw3mfmhdxminf2kla3dp4ndsz23bnry/lib -Wl,-rpath,/Users/4s2/programs/geant4/install-v1103/lib  lib/libaccel.dylib  /Users/4s2/programs/root/install/lib/libTree.so  lib/libceleritas.dylib  /Users/Shared/ornldev/code/spack/opt/spack/darwin-monterey-skylake/apple-clang-14.0.0/vecgeom-1.2.3-orw3mfmhdxminf2kla3dp4ndsz23bnry/lib/libvecgeom.dylib  lib/libcorecel.dylib  /Users/Shared/ornldev/code/spack/opt/spack/darwin-monterey-skylake/apple-clang-14.0.0/openmpi-4.1.5-lbbmodybuodqy2ot6iwaxmr3qtap3f5j/lib/libmpi.dylib  /Users/4s2/programs/geant4/install-v1103/lib/libG4Tree.dylib  /Users/4s2/programs/geant4/install-v1103/lib/libG4FR.dylib  /Users/4s2/programs/geant4/install-v1103/lib/libG4GMocren.dylib  /Users/4s2/programs/geant4/install-v1103/lib/libG4visHepRep.dylib  /Users/4s2/programs/geant4/install-v1103/lib/libG4RayTracer.dylib  /Users/4s2/programs/geant4/install-v1103/lib/libG4VRML.dylib  /Users/4s2/programs/geant4/install-v1103/lib/libG4vis_management.dylib  /Users/4s2/programs/geant4/install-v1103/lib/libG4modeling.dylib  /Users/4s2/programs/geant4/install-v1103/lib/libG4interfaces.dylib  /usr/local/opt/qt@5/lib/QtWidgets.framework/QtWidgets  /usr/local/opt/qt@5/lib/QtGui.framework/QtGui  /usr/local/opt/qt@5/lib/QtCore.framework/QtCore  /Users/4s2/programs/geant4/install-v1103/lib/libG4persistency.dylib  /usr/local/lib/libxerces-c.dylib  /Users/4s2/programs/geant4/install-v1103/lib/libG4error_propagation.dylib  /Users/4s2/programs/geant4/install-v1103/lib/libG4readout.dylib  /Users/4s2/programs/geant4/install-v1103/lib/libG4physicslists.dylib  /Users/4s2/programs/geant4/install-v1103/lib/libG4tasking.dylib  /Users/4s2/programs/geant4/install-v1103/lib/libG4run.dylib  /Users/4s2/programs/geant4/install-v1103/lib/libG4event.dylib  /Users/4s2/programs/geant4/install-v1103/lib/libG4tracking.dylib  /Users/4s2/programs/geant4/install-v1103/lib/libG4parmodels.dylib  /Users/4s2/programs/geant4/install-v1103/lib/libG4processes.dylib  /Users/4s2/programs/geant4/install-v1103/lib/libG4analysis.dylib  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/lib/libexpat.tbd  /Users/4s2/programs/geant4/install-v1103/lib/libG4digits_hits.dylib  /Users/4s2/programs/geant4/install-v1103/lib/libG4track.dylib  /Users/4s2/programs/geant4/install-v1103/lib/libG4particles.dylib  /Users/4s2/programs/geant4/install-v1103/lib/libG4geometry.dylib  /Users/4s2/programs/geant4/install-v1103/lib/libG4materials.dylib  /Users/4s2/programs/geant4/install-v1103/lib/libG4graphics_reps.dylib  /Users/4s2/programs/geant4/install-v1103/lib/libG4intercoms.dylib  /Users/4s2/programs/geant4/install-v1103/lib/libG4global.dylib  /Users/4s2/programs/geant4/install-v1103/lib/libG4tools.dylib  /Users/4s2/programs/geant4/install-v1103/lib/libG4clhep.dylib  /Users/4s2/programs/geant4/install-v1103/lib/libG4zlib.dylib  /Users/4s2/programs/geant4/install-v1103/lib/libG4ptl.0.0.2.dylib  /Users/4s2/programs/root/install/lib/libMathCore.so  /Users/4s2/programs/root/install/lib/libImt.so  /Users/4s2/programs/root/install/lib/libMultiProc.so  /Users/4s2/programs/root/install/lib/libNet.so  /Users/4s2/programs/root/install/lib/libRIO.so  /Users/4s2/programs/root/install/lib/libThread.so  /Users/4s2/programs/root/install/lib/libCore.so && :
Undefined symbols for architecture x86_64:
  "celeritas::app::GlobalSetup::Instance()", referenced from:
      celeritas::app::HitRootIO::HitRootIO() in HitRootIO.cc.o
      celeritas::app::HitRootIO::WriteObject(celeritas::app::HitRootEvent*) in HitRootIO.cc.o
  "celeritas::app::SensitiveHit::allocator()", referenced from:
      celeritas::app::SensitiveHit::operator new(unsigned long) in HitClassesRootInterfaces.cxx.o
      celeritas::app::SensitiveHit::operator delete(void*) in HitClassesRootInterfaces.cxx.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

**Comment by mrguilima** [comment]
On my MacOS, I also see the same thing as Stefano, but with two more lines:
```
ld: Undefined symbols:
  celeritas::app::GlobalSetup::Instance(), referenced from:
      celeritas::app::HitRootIO::HitRootIO() in HitRootIO.cc.o
      celeritas::app::HitRootIO::WriteHits(G4Event const*) in HitRootIO.cc.o
      celeritas::app::HitRootIO::WriteObject(celeritas::app::HitRootEvent*) in HitRootIO.cc.o
  celeritas::app::SensitiveHit::allocator(), referenced from:
      ROOT::new_celeritascLcLappcLcLSensitiveHit(void*) in HitClassesRootInterfaces.cxx.o.     <----
      ROOT::delete_celeritascLcLappcLcLSensitiveHit(void*) in HitClassesRootInterfaces.cxx.o. <----
      celeritas::app::SensitiveHit::operator delete(void*) in HitClassesRootInterfaces.cxx.o
      celeritas::app::SensitiveHit::~SensitiveHit() in HitClassesRootInterfaces.cxx.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by sethrj** [comment]
@pcanal @stognini Would it be reasonable for us to have a standard "SD hit output" object that we keep in `celeritas/io` and use in our `celer-g4` app? That could make it easier for us to, say, export hits directly from CPU through `celer-sim` and compare performance, in addition to making it easier to use the output from celer-g4.

**Comment by sethrj** [comment]
@pcanal @stognini This will be replaced by Stefano's work to put in a "hit output" in `celeritas/io` right? This was just a temporary hack to get out CMS verifiction data in time for the geant4 presentation, wasn't it?

**Comment by stognini** [comment]
I made a similar update on my [branch](https://github.com/stognini/celeritas/blob/decouple-g4vhit-data/app/celer-g4/CMakeLists.txt) to get a dictionary for testing my decoupling of classes/data. So we will need a dictionary anyway. I guess the question is: are we fine with the dictionary being generated this way, or is there something else planned? The main difference between here and my branch is that my [HitClassesLinkDef](https://github.com/stognini/celeritas/blob/decouple-g4vhit-data/app/celer-g4/HitClassesLinkDef.h), and therefore the final dictionary, is much simpler, with just structs with basic types.

**Comment by sethrj** [comment]
Let's stick with @stognini 's branch; simpler structs are better too. Also,  didn't we discuss putting the dictionary code in `celeritas/io`? The way ROOT works, we kind of need the dictionaries to sit alongside the libraries, right?

**Comment by pcanal** [comment]
> we kind of need the dictionaries to sit alongside the libraries, right?

Not completely necessary but much easier.

**Pull request closed without merging**
