### PR TITLE
Fix dBVH memcpy size

### PR DESCRIPTION
**Pull request by esseivaju**
Introduced in #1481, copy the entire pointer instead of 1 byte.

### CODE REVIEW

**Review by pcanal — APPROVED** [review]
Thanks for finding this!

**Comment by esseivaju** [comment]
Missed that in the review, better late than never 😅

**Comment by pcanal** [comment]
Does it fix the crash related to `dBVH`?

**Comment by sethrj** [comment]
This was only for the diagnostic. Sorry I didn't notice it!

**Comment by esseivaju** [comment]
right, it's only for the diagnostic, and that line is still showing up in a full static build of AthSimulation+AthExternals

**Pull request merged**
