### PR TITLE
Rewrite field tests including two failing ones

### PR DESCRIPTION
**Pull request by sethrj**
The existing field tests are as much for performance testing than anything. I've deleted most of the CUDA components (since the CUDA and C++ code are essentially identical) and added more refined testing including more edge cases. Two of the added tests fail (at least with debug + ORANGE) and I've marked them as disabled (they can be run with `./test/celeritas_field_FieldPropagator --gtest_also_run_disabled_tests`):
```
[ RUN      ] TwoBoxTest.DISABLED_electron_tangent_cross
/Users/seth/.local/src/celeritas/test/celeritas/field/FieldPropagator.test.cc:443: Failure
Value of: result.distance
  Actual: 6.2831853071795862
Expected: circ / 4
Which is: 1.5707963267948966
(Relative error 3 exceeds tolerance 9.9999999999999998e-13)
Google Test trace:
/Users/seth/.local/src/celeritas/test/celeritas/field/FieldPropagator.test.cc:436: Barely hits boundary
/Users/seth/.local/src/celeritas/test/celeritas/field/FieldPropagator.test.cc:444: Failure
Value of: result.boundary
  Actual: false
Expected: true
Google Test trace:
/Users/seth/.local/src/celeritas/test/celeritas/field/FieldPropagator.test.cc:436: Barely hits boundary
/Users/seth/.local/src/celeritas/test/celeritas/field/FieldPropagator.test.cc:445: Failure
Expected: (distance(Real3({0, 5, 0}), geo.pos())) < (1e-5), actual: 1.41352 vs 1e-05
Google Test trace:
/Users/seth/.local/src/celeritas/test/celeritas/field/FieldPropagator.test.cc:436: Barely hits boundary
/Users/seth/.local/src/celeritas/test/celeritas/field/FieldPropagator.test.cc:446: Failure
Expected: (distance(Real3({-1, 0, 0}), geo.dir())) < (1e-5), actual: 1.41422 vs 1e-05
Google Test trace:
/Users/seth/.local/src/celeritas/test/celeritas/field/FieldPropagator.test.cc:436: Barely hits boundary
[  FAILED  ] TwoBoxTest.DISABLED_electron_tangent_cross (0 ms)
[ RUN      ] TwoBoxTest.DISABLED_nonuniform_field
unknown file: Failure
C++ exception with description "/Users/seth/.local/src/celeritas/src/corecel/math/Algorithms.hh:118:
celeritas: precondition failed: !(hi < lo)" thrown in the test body.
[  FAILED  ] TwoBoxTest.DISABLED_nonuniform_field (0 ms)
```

The first one starts an electron so that at the top of its arc it should barely exit the region almost at a tangent.  (At the top of its arc it should be ~1e-3 cm inside the new region.) Instead it skips it completely.

The second failure is an assertion inside the field driver that fails when calculating a new step length. The distance between `end_curve_length` and `curve_length` is nearly zero, which is greater than the minimum step of 1e-6, and the driver is still proposing a new step rather than exiting the loop.

I *think* these are both bugs (edge cases) but would appreciate another set of eyes. I don't think either of these bugs is responsible for the magnetic field boundary crossing failures (mfp > 0 assertion) that we're seeing... but adding more detailed boundary crossing tests I think was a worthwhile prerequisite to that.

See #460

### CODE REVIEW

**Comment by whokion** [comment]
With Vecgeom, there are failures from celeritas_field_FieldPropagator on my setup at VecgeomParams.cc:135:
`celeritas: internal assertion failed: world_top_devptr != nullptr" thrown in SetUp().`  Have you seen this?

**Comment by sethrj** [comment]
Yep, sorry @whokion : I selected the wrong volume as the world boundary. I've fixed another test too (stupid error from changing the two-boxes problem) and reintroduced the "circles through the CMS parameterized field" test.

**Comment by sethrj** [comment]
@whokion The failure in `TwoBoxTest.DISABLED_nonuniform_field` is one I'm also seeing in testem3 with magnetic field:
the input file 
```json
{"geometry_filename": "input/testem3-flat.gdml",
 "physics_filename": "input/testem3-flat.gdml",
 "seed": 12345,
 "enable_diagnostics": false,
 "sync": false,
 "secondary_stack_factor": 3,
 "max_steps": 1073741824,
 "eloss_fluctuation": false,
 "brem_combined": false,
 "brem_lpm": true,
 "rayleigh": false,
 "energy_diag": {"axis": "x", "min": -20, "max": 20, "num_bins": 50},
 "geant_options": {"physics": "em_basic", "em_bins_per_decade": 56},
 "mag_field": [1000, 0, 0],
 "max_num_tracks": 64,
 "initializer_capacity": 32768,
 "use_device": false,
 "hepmc3_filename": "input/testem3.10k.hepmc3",
 "enable_msc": false,
 "conv_lpm": true
}
```
dies because the "minimum step" is greater than the difference between the curve and end_curve lengths:
```
frame #3: 0x00007ffff5acf24e libceleritas.so`celeritas::FieldDriver<celeritas::DormandPrinceStepper<celeritas::MagFieldEquation<celeritas::UniformField> > >::accurate_advance(this=0x00007ffffffeed30, step=0.23558772294033617, state=0x00007ffffffeed60, hinitial=0.087902712077450498) const at FieldDriver.hh:261:22
   258 	        }
   259 	        else
   260 	        {
-> 261 	            h = clamp(output.proposed_step,
   262 	                      options_.minimum_step,
   263 	                      end_curve_length - curve_length);
   264 	        }
(lldb) frame variable
(const celeritas::FieldDriver<celeritas::DormandPrinceStepper<celeritas::MagFieldEquation<celeritas::UniformField> > > *const) this = 0x00007ffffffeed30
(celeritas::real_type) step = 0.23558772294033617
(const celeritas::OdeState &) state = 0x00007ffffffeed60: {
  pos = {
    data_ = ([0] = -12.999483680194793, [1] = -0.0083757301053206112, [2] = -0.0026841491322111043)
  }
  mom = {
    data_ = ([0] = 1.4457787112433322, [1] = -0.087117080738992977, [2] = 0.3173430235222941)
  }
}
(celeritas::real_type) hinitial = 0.087902712077450498
(celeritas::real_type) end_curve_length = 0.23558772294033617
(celeritas::real_type) h = 0.14768501086288566
(celeritas::real_type) h_threshold = 0.0000023558772294033618
(celeritas::FieldDriver<celeritas::DormandPrinceStepper<celeritas::MagFieldEquation<celeritas::UniformField> > >::Integration) output = {
  end = {
    state = {
      pos = {
        data_ = ([0] = -12.769771432528691, [1] = -0.033482874057291771, [2] = 0.042617024397261317)
      }
      mom = {
        data_ = ([0] = 1.4457787112433322, [1] = -0.22292658236584373, [2] = 0.24207369953508154)
      }
    }
    step = 0.14768501086288566
  }
  proposed_step = 0.49706047069083242
}
(bool) succeeded = false
(celeritas::real_type) curve_length = 0.23558772294033614
(celeritas::size_type) remaining_steps = 99
```

**Comment by sethrj** [comment]
See #399: you'd corrected the "accurate advance"  calculation to
```
min(max(proposed, min_step), remaining)
```
which I changed to `clamp(proposed, min_step, remaining)`, which isn't quite the same since remaining can clearly be less than `min_step`.

I'd like to have some additional testing on the field driver, which currently uses only tests a single `hstep` value, which clearly isn't enough...

**Review by whokion — APPROVED** [review]
@sethrj Good to merge for now. I will also take a look at the failed case.

**Comment by whokion** [comment]
@sethrj I looked the failed case (skipping boundary) which is due to, at least, a wrong logic to flag linear_step.boundary with the chord direction obtained by the driver. i.e., at the [line](https://github.com/celeritas-project/celeritas/blob/master/src/celeritas/field/FieldPropagator.hh#L154) and the one below.  As you know, the driver itself does not know whether the integrated trajectory for the given step is crossing a boundary or not, but simply advances a given full step or sub-steps within the given accuracy and updates the state.  So, the current logic for handling the boundary crossing (which was introduced during the code refactoring) does not work when the final sub-step position after integrating a given (sub)step returns to the same volume after the crossing a boundary - there may be other cases of which the final direction is pointing to wrong surfaces.  Other failures in the same test are related and due to the same reason that the propagator is not stopping at the right boundary (and additionally, due to the extra 1e-3 shift in the y-position will make rather large differences in x-position and direction along the tangential line near pi/2 even finding the right intersection point. I also find that you removed the use of safety in the propagator after refactoring, which seems to be a radical short cut (great if it works, but need to prove the logic without it).  Anyway, I will leave this issue to you as the code has been changed significantly from the original version, especially for the logic of handling the intersection.

**Comment by sethrj** [comment]
Aha, thanks for looking into the error @whokion . The removal of the safety calculation in #333 wasn't primarily a shortcut; it was an attempt at a simpler, more understandable algorithm (and to reduce the substantial duplication between "query" and "find" intersection); and because ORANGE at that point had just learned to find boundary crossings but didn't have any support for safety distances. We can discuss more at the meeting today.

**Comment by whokion** [comment]
@sethrj As I looked this issue again, I should admit that the original implementation was not handling the failure case properly either - I might assume that`ComputeStep` at this [line](https://geant4.kek.jp/lxr/source/geometry/navigation/include/G4VIntersectionLocator.icc#L142) was simply the distance by the `LinearPropagator` which is wrong.  I will investigate missing logic inside [ComputeStep](https://geant4.kek.jp/lxr/source/geometry/navigation/src/G4NormalNavigation.cc#L64) and we discuss relevant extensions (probably including a potential use of safety?) later.

**Comment by sethrj** [comment]
I also admit to not being thorough about writing up the new propagation algorithm: I will make a to-do to add cartoons with the various step conditions and a flow chart for the overall behavior. I was looking at the field driver in detail and think that it might be useful to break some of its components up into "detail" classes for increased testing... and maybe adding some fictional nonuniform magnetic fields inside the driver test.

**Pull request merged**
