### PR TITLE
Extend UrbanMsc verification with TestEM15

### PR DESCRIPTION
**Pull request by whokion**
This MR extends physics verification of the Urban multiple scattering model with respect to the Geant4 TestEM15 (extended) example.

### CODE REVIEW

**Comment by sethrj** [comment]
I'll need to generate an ORANGE input file for this to pass. This afternoon/evening :)

**Comment by whokion** [comment]
@sethrj No hurry! I was trying to test the branch before requesting your review.  Thanks.

**Comment by whokion** [comment]
@sethrj so, it looks that values of find_safety() from orange are not consistence with VecGeom (Geant4), which is causing the test failure.

**Comment by sethrj** [comment]
I accidentally flipped the sizes of the two boxes—but unless that caused the safety to report as zero for some reason, why would it make a difference? Would a difference in the safety distance between 50 meters and 600 meters really change the MSC step length?

**Comment by whokion** [comment]
> I accidentally flipped the sizes of the two boxes—but unless that caused the safety to report as zero for some reason, why would it make a difference? Would a difference in the safety distance between 50 meters and 600 meters really change the MSC step length?

It may depend what the current safety value and the range are.  In the current test case, the safety value (1e-8cm) from the first evaluation at the starting position may affect the msc limit calculation as it is really close to the boundary - please see [this line](https://github.com/whokion/celeritas/blob/msc-testem15/src/celeritas/em/distribution/UrbanMscStepLimit.hh#L204).  Anyway, the test with the updated orange geometry is successfuk, at least, on my test platform.

**Comment by whokion** [comment]
Okay, let's close this MR without merging as I already grasp a good idea on the overall performance of this test.  The reason that I did not use CoreParams was to minimize data needed for this test (still significant, ~60%).  Anyway, taking out ~60% of time that goes for H2D and D2H, the relative gain (one cpu core vs v100) is around 50 for the test, which is significantly poor compared to the overall performance of demo-loop without msc, but still may not explain the overall performance of the demo-loop with msc (i.,e not too poor), which need further investigation.

**Pull request closed without merging**
