### PR TITLE
Fix uniform field unit conversion

### PR DESCRIPTION
**Pull request by amandalund**
Well that's why our celer-g4 performance results with a uniform field looked suspiciously good...

### CODE REVIEW

**Review by sethrj — APPROVED** [review]
My bad for missing this in the last review... is it possible to add a unit test for the along-step factory? At some point we'll need to add something more than a "does it run" test for the front end apps too.

**Comment by amandalund** [comment]
I don't _think_ I changed the field units when I refactored for the json input (except for messing up the `magnitude_tesla`), but I definitely should have caught this. Yeah, an along-step factory test is a good idea (and agreed about our app tests).

**Comment by sethrj** [comment]
Is this bug present in v0.3?

**Comment by amandalund** [comment]
Yep, looks like it is.

**Comment by sethrj** [comment]
Damn, you're right. Thanks for the catch.

**Comment by sethrj** [comment]
Yeah, the unit error was in the original #702 . It just got *moved* in #890 .

**Pull request merged**
