### PR TITLE
Refactor primaries as `aux` data

### PR DESCRIPTION
**Pull request by sethrj**
Almost none of the stepping loop has to access the primaries, and right now the storage and usage of them is split across the CoreState and the ExtendFromPrimariesAction (EFPA). This PR refactors the primary storage, removing it from the main state and adding it as "aux" data to the EFPA. It's expected that the higher-level code (whether optical transport or core transport) determines whether primaries are to be used as the source of track initializers: for example, we could use a generalized source description to generate track initializers on device.

This completes the first part of #1390.

### CODE REVIEW

**Comment by sethrj** [comment]
@amandalund This is finally all fixed and working!

**Comment by amandalund** [comment]
Sorry for the delay! Looking at this today.

**Comment by sethrj** [comment]
No worries!

**Review by amandalund — APPROVED** [review]
Nice refactor! All looks good to me, thanks @sethrj.

**Pull request merged**
