### PR TITLE
Lima/geom

### PR DESCRIPTION
**Pull request by mrguilima**
Add classes LinearPropagationHandler and FieldPropagationHandler.

### CODE REVIEW

**Comment by sethrj** [comment]
@mrguilima Before I review this branch, I think three main changes would be very helpful:
1. Restrict the scope to requirements for the propagation itself, not for how the propagation ties into the larger stepping algorithms. For example, propagation doesn't require simulation time, so that should be a separate change set.
2. Use formatting consistent with the guidelines and the rest of the project. This includes changing function and variable names to using `snake_case` rather than `camelCase`, and ensuring that there's no "dead code" (e.g. commented-out blocks).
3. Use clang-format to format your code changes -- there's a script in `scripts/dev/install-commit-hooks.sh` to install a git commit hook that will auto-format each commit.  You can use a `git rebase` to retroactively apply those after installing.

Thanks!

**Comment by mrguilima** [comment]
I tried to run `scripts/dev/install-commit-hooks.sh` before, but clang-format is not installed on this system.
`spack install clang-format` does not work.  I am not sure how to proceed regarding this clang-format suggestion.

**Comment by sethrj** [comment]
Ah, that rings a bell. Clang format is part of llvm, which you can install through spack.

**Comment by mrguilima** [comment]
Well yes, I know, but installing llvm because of clang-format is too much!  I have done in the past installing only clang-format, by hand, and I remember I had to learn some tricks.  It would be nice to have spack install only clang-format...

**Comment by sethrj** [comment]
I agree; it's very annoying to build all of LLVM for clang-format, and then  to build another copy of LLVM to build into ROOT.

I thought that there was an open spack request for "clang-format without llvm" but can't find it. Homebrew can do an independent clang-format installation, so if you have that on your mac  then you can use `brew install clang-format` to get a copy.

**Comment by mrguilima** [comment]
I have a brew-installed clang-format in my Mac laptop, but copying just that binary over to lq cluster (linux) does not work.
I am googling up what is involved to build clang-format without building the whole llvm.

**Comment by mrguilima** [comment]
This PR is replaced with !38.  Closing it.

**Pull request closed without merging**
