### PR TITLE
Fix indexing of imported micro xs

### PR DESCRIPTION
**Pull request by amandalund**
In #481 we switched from using a map indexed by element ID to a vector indexed by element component ID for the imported micro xs, but this wasn't correctly updated in the `ImportedModelAdaptor` -- should be fixed here.

### CODE REVIEW

**Comment by stognini** [comment]
😱 
Wow, sorry I missed that!

**Comment by amandalund** [comment]
> 😱 Wow, sorry I missed that!

nah, remember it's @sethrj's fault for not catching it in the review (ok and mine too :))

**Comment by sethrj** [comment]
Are there any new tests that will work with the fix but fail with master? Would that require a new root file with mixed elements? A multi element stepper test? I'm surprised we didn't catch this...

**Comment by amandalund** [comment]
Ahh wait we also sort the material components by element ID in the `MaterialParams` constructor, but not in the importer, so the material elcomp IDs won't necessarily correspond to the same elements as the imported elcomp IDs, right?

**Comment by sethrj** [comment]
Uh oh, yes we should be doing that too

**Comment by amandalund** [comment]
@sethrj damn if we had tested the micro xs builders in the `ImportedProcesses` test that would have caught it, since four-steel-slabs has a material with three elements — I added some checks in there, but let me know if you can think of another test that would help.

**Review by sethrj — APPROVED** [review]
Nice work, @amandalund . Thanks for finding and fixing!

**Pull request merged**
