### PR TITLE
Improve and fix Geant4 volume conversion on boundaries

### LINKED ISSUE #891: Fix or output "lost energy" warnings on boundaries
@whokion reports seeing numerous errors during sensitive detector callback. A JSON output entry of expected volumes and associated points would help debugging potential geometry issues.

### PR DESCRIPTION
**Pull request by sethrj**
When reconstructing a G4Step object from a GPU hit, we have to find the Geant4 physical volume based on the position and direction, and it needs to match the logical volume of the hit detector. This can lead to ambiguities when reinitializing on boundaries. Before, we'd only bump in the forward direction to see if the boundary is crossed. Now, we bump both directions, and intelligently switch the direction of the first boundary tested if the safety distance is smaller than the next distance.

Closes #891.

### CODE REVIEW

**Comment by sethrj** [comment]
@whokion Could you see if this gets rid of most/all of the warnings for your CMSSW use case?

**Comment by whokion** [comment]
@sethrj I have a following compilation error:
```
In file included from /work1/celeritas/syjun/celeritas/src/celeritas/src/celeritas/ext/g4vg/SolidConverter.cc:86:
/work1/celeritas/syjun/celeritas/src/celeritas/src/corecel/math/Algorithms.hh: In instantiation of ‘constexpr T celeritas::ipow(T) [with unsigned int N = 0; T = double]’:
/work1/celeritas/syjun/celeritas/src/celeritas/src/corecel/math/Algorithms.hh:425:37:   recursively required from ‘constexpr T celeritas::ipow(T) [with unsigned int N = 1; T = double]’
/work1/celeritas/syjun/celeritas/src/celeritas/src/corecel/math/Algorithms.hh:425:37:   required from ‘constexpr T celeritas::ipow(T) [with unsigned int N = 3; T = double]’
/work1/celeritas/syjun/celeritas/src/celeritas/src/celeritas/ext/g4vg/SolidConverter.cc:757:47:   required from here
/work1/celeritas/syjun/celeritas/src/celeritas/src/corecel/math/Algorithms.hh:413:35: error: parameter ‘v’ set but not used [-Werror=unused-but-set-parameter]
  413 | CELER_CONSTEXPR_FUNCTION T ipow(T v) noexcept
```

**Comment by sethrj** [comment]
Ugh, this is a bug in GCC that @tmdelellis also saw. Let me cherry-pick the fix onto this branch.

**Comment by whokion** [comment]
Not sure about whether the frequency of this warning is reduced (will check with the latest develop), but there are still remaining cases ( 216 cases while running 20 ttbar without field), for an example,
```
G4WT1 > TouchableUpdater.cc:96: [2/2] warning: Bumping navigation state by 0.026593580928623 [mm] because the pre-step point at {-42.80103732245, 218.78549484378, -3982.5110083569} [mm] along {0.63174066101431, -0.65540130963853, 0.41394789593052} is expected to be in logical volume "caloBase_CALO"@0x383a3d0 (ID=2649) but navigation gives {{pv='hcalalgo_HCal_1', lv=2648='hcalalgo_HCal'} -> {pv='caloBase_CALO_1', lv=2649='caloBase_CALO'} -> {pv='cms_CMSE_1', lv=4593='cms_CMSE'} -> {pv='cms_OCMS_1', lv=4594='cms_OCMS'}}
G4WT1 > TouchableUpdater.cc:148: [2/2] warning: Failed to bump navigation state up to a distance of 1 [mm]
G4WT1 > HitProcessor.cc:222: [2/2] error: Omitting energy deposition of 3.8725e-11 [MeV]
```

**Comment by sethrj** [comment]
It should definitely be fixed with simple CMS at least... 😅

**Comment by whokion** [comment]
Running the current develop (with the fix Algorithms.hh), I see 260 cases of
"352: warning: Failed to bump navigation state up to a distance of 1 [mm]" with the same configuration (run3, 20 ttbar, no field), for an example,
```
/work1/celeritas/syjun/celeritas/src/celeritas/src/accel/detail/HitProcessor.cc:
352: warning: Failed to bump navigation state up to a distance of 1 [mm]
/work1/celeritas/syjun/celeritas/src/celeritas/src/accel/detail/HitProcessor.cc:
359: error: expected step point at {290.28504900673, -135.69152634243, -3982.5} 
[mm] along {0.43629640513787, 0.89551923763144, -0.087696875062822} to be in log
ical volume "caloBase_CALO"@0x3454be0 (ID=2649) but navigation gives {{pv='hcala
lgo_HCal_1', lv=2648='hcalalgo_HCal'} -> {pv='caloBase_CALO_1', lv=2649='caloBas
e_CALO'} -> {pv='cms_CMSE_1', lv=4593='cms_CMSE'} -> {pv='cms_OCMS_1', lv=4594='
cms_OCMS'}}: omitting energy deposition of 0.00126778 [MeV]

```
So, it helps little bit (260->216 cases), but the issue seems not completely be resolved.

**Comment by whokion** [comment]
Running with app/celer-g4/simple-cms-test.inp.json, I still see two cases:
```
G4WT1 > TouchableUpdater.cc:96: [2/2] warning: Bumping navigation state by 0.15847742453298 [mm] because the pre-step point at {128.83413807803, -270.82102012142, -2672.7505039643} [mm] along {0.77015590259216, -0.30608417592167, -0.55961805095334} is expected to be in logical volume "si_tracker"@0x27ba3b0 (ID=1) but navigation gives {{pv='vacuum_tube_pv', lv=0='vacuum_tube'}}
and
G4WT1 > TouchableUpdater.cc:96: [2/2] warning: Bumping navigation state by 0.5682451488365 [mm] because the pre-step point at {-206.25679395806, -217.74488354803, -954.9663190649} [mm] along {0.61713971785822, -0.76637525189352, 0.17834669026092} is expected to be in logical volume "si_tracker"@0x27ba3b0 (ID=1) but navigation gives {{pv='vacuum_tube_pv', lv=0='vacuum_tube'}}
```

**Comment by sethrj** [comment]
Hmmm ok. Thanks @whokion I'll  investigate further.

**Comment by amandalund** [comment]
With simple-cms running with more primaries I also see some errors, e.g.:
```console
G4WT0 > TouchableUpdater.cc:148: [1/2] warning: Failed to bump navigation state up to a distance of 1 [mm]
G4WT0 > HitProcessor.cc:222: [1/2] error: Omitting energy deposition of 1.01532 [MeV]
```

**Comment by sethrj** [comment]
Thanks peeps. I'll see if I can reproduce in that unit test. It's possible there's an issue due to latent state information in the navigator...

**Comment by sethrj** [comment]
@whokion This could be an actual vecgeom tracking problem: the points you gave have `r = 29.990` cm and `r = 29.992` cm... when the boundary is at `r = 30`. That's very odd.

@amandalund Can you please re-run with the latest update that gives improved detailed output?

**Comment by sethrj** [comment]
The VecGeom `kBoundaryPush` is ~1e-8 so that shouldn't give this big a discrepancy in the boundary crossing.

**Comment by amandalund** [comment]
@sethrj here are a few with the detailed output:
```console
G4WT1 > TouchableUpdater.cc:156: [2/2] warning: Failed to bump navigation state up to a distance of 1 [mm] at {-427.56983454727, 1174.5995217837, 747.90972779276} [mm] along {-0.70886981480525, 0.21169894981561, 0.67282028826793} to try to reach "em_calorimeter"@0x11f1310 (ID=2): found {{pv='si_tracker_pv', lv=1='si_tracker'}}
G4WT1 > HitProcessor.cc:222: [2/2] error: Omitting energy deposition of 0.0585255 [MeV]
G4WT0 > TouchableUpdater.cc:156: [1/2] warning: Failed to bump navigation state up to a distance of 1 [mm] at {-1175.9420796891, 424.47404011144, 747.17772704325} [mm] along {0.46254766852101, 0.83983515631001, -0.28412420624001} to try to reach "si_tracker"@0x11f1200 (ID=1): found {{pv='em_calorimeter_pv', lv=2='em_calorimeter'}}
G4WT0 > HitProcessor.cc:222: [1/2] error: Omitting energy deposition of 3.41432e-13 [MeV]
G4WT1 > TouchableUpdater.cc:156: [2/2] warning: Failed to bump navigation state up to a distance of 1 [mm] at {-180.84752203436, -1236.8514741857, 80.959574210285} [mm] along {-0.34086888072834, 0.082800146878107, 0.93645744261444} to try to reach "si_tracker"@0x11f1200 (ID=1): found {{pv='em_calorimeter_pv', lv=2='em_calorimeter'}}
G4WT1 > HitProcessor.cc:222: [2/2] error: Omitting energy deposition of 4.91316e-13 [MeV]
```

**Comment by whokion** [comment]
> @whokion This could be an actual vecgeom tracking problem: the points you gave have `r = 29.990` cm and `r = 29.992` cm... when the boundary is at `r = 30`. That's very odd.

The end point is at r = 299.99999999989865 mm and r = 299.9999999999009 mm after the bump, which are still in the vacuum_tube (rmax="299.9999999999") as they are still less than 30 cm (???). Looks that the numerical precision may be a potential issue (???).

**Comment by whokion** [comment]
> @sethrj here are a few with the detailed output:
> 
> ```
> G4WT1 > TouchableUpdater.cc:156: [2/2] warning: Failed to bump navigation state up to a distance of 1 [mm] at {-427.56983454727, 1174.5995217837, 747.90972779276} [mm] along {-0.70886981480525, 0.21169894981561, 0.67282028826793} to try to reach "em_calorimeter"@0x11f1310 (ID=2): found {{pv='si_tracker_pv', lv=1='si_tracker'}}
> G4WT1 > HitProcessor.cc:222: [2/2] error: Omitting energy deposition of 0.0585255 [MeV]
> G4WT0 > TouchableUpdater.cc:156: [1/2] warning: Failed to bump navigation state up to a distance of 1 [mm] at {-1175.9420796891, 424.47404011144, 747.17772704325} [mm] along {0.46254766852101, 0.83983515631001, -0.28412420624001} to try to reach "si_tracker"@0x11f1200 (ID=1): found {{pv='em_calorimeter_pv', lv=2='em_calorimeter'}}
> G4WT0 > HitProcessor.cc:222: [1/2] error: Omitting energy deposition of 3.41432e-13 [MeV]
> G4WT1 > TouchableUpdater.cc:156: [2/2] warning: Failed to bump navigation state up to a distance of 1 [mm] at {-180.84752203436, -1236.8514741857, 80.959574210285} [mm] along {-0.34086888072834, 0.082800146878107, 0.93645744261444} to try to reach "si_tracker"@0x11f1200 (ID=1): found {{pv='em_calorimeter_pv', lv=2='em_calorimeter'}}
> G4WT1 > HitProcessor.cc:222: [2/2] error: Omitting energy deposition of 4.91316e-13 [MeV]
> ```

The second case is strange as both the start point (r=1250.2071770358918 mm) and the end after the bump (r=1250.0576077503752) are inside `calorimeter`.  The first (third) case after the bump should be in `calorimeter` (si_tracker) as supposed to be, but found at `si_tracker` (calorimeter) - so, why?.

**Comment by sethrj** [comment]
The pre-bump point is the beginning step, which should be in the expected volume. Because we're using the Geant4 navigator, the post-bump point can still be a different volume even though the radius is slightly out of range. (This is true of any navigator, where the logical state [volume ID] and physical state [position] may be slightly inconsistent due to roundoff.)

**Comment by whokion** [comment]
The first case is kind of understandable as the pre-bump point is at r=1249.9999999957106 mm (very close to  rmax="1249.9999999999" of si_tracker, but the pre-bump point of the third case is at r=1250.0029581650226 mm which seems to be far away to be found inside the calorimeter (rmin="1250") by the Geant4 navigator.  BTW, Geant4 should have used the VecGeom navigator when VecGeom is used - I know that this was one of plans of work for 11.2, but do not know whether it is actuall ready (@mrguilima, do you know the status?).

**Comment by sethrj** [comment]
OK thanks @whokion and @amandalund . I fixed a bug that solves 4 out of the 5 failures. The last one seems to be due to some points that are too coincident for Geant4's navigator to find a crossing.

**Comment by amandalund** [comment]
> I fixed a bug that solves 4 out of the 5 failures. The last one seems to be due to some points that are too coincident for Geant4's navigator to find a crossing.

Yep, confirmed that that got rid of ~85% of the errors with simple-cms.

**Comment by sethrj** [comment]
Great. I think further improvements (which might require new navigation magic?) should be a follow on. Maybe a separate one to write out the failed points by volume.

**Comment by mrguilima** [comment]
>  BTW, Geant4 should have used the VecGeom navigator when VecGeom is used - I know that this was one of plans of work for 11.2, but do not know whether it is actuall ready (@mrguilima, do you know the status?).

@sethrj, as far as I know, the effort to make VecGeom navigator available for Geant4 was suspended due to not enough interest on it, considering the amount of work needed to finish it.

**Review by amandalund — APPROVED** [review]
Thanks @sethrj, this looks good to me!

**Pull request merged**
